### ISSUE TITLE
[Feature Request] Config option for crafting recipe

### ISSUE THREAD

**Issue by Ultimushadow** [Darkhax-Minecraft/Archaeology-Banners#2]
I think a crafting recipe enabled via config would be a cool idea for the patterns rather than being traded for, something like charcoal/coal, paper, and the sherd you want to make a pattern from. Preferably the sherd would not be consumed, as the idea would be making a charcoal/coal rub to get the pattern directly off the sherd. I will end up making this as a datapack for myself anyways, but I figured it would be fun to add as an option, if you want the .json files I can link them here after I get everything filled out!

**Comment by Darkhax** [comment]
Thanks for the feature request, this was meant to already be a feature however there was a bug preventing the recipes from loading on 1.20+. The intended recipe is paper plus a sherd however the sherd is consumed in the recipe. Consuming the sherd is in line with other vanilla pattern recipes and Minecraft's recipe framework only supports items being globally non-consumable like buckets so implementing that would cause issues with other recipes that use the sherd. I did make a mod called [Sherd Duplication](https://curseforge.com/minecraft/mc-mods/sherd-duplication) that adds a recipe similar to the vanilla armor trip copying recipe though.

**Comment by Ultimushadow** [comment]
Oh I didn't even realize that was an intended feature! Welp, I'll still be using my datapack because I like the coal/charcoal idea but at least it's documented now
And yeah the consuming the sherd thing is probably more work than it's worth, I also made a duplication pack for myself when the update dropped lol

**Comment by Darkhax** [comment]
This has been fixed in the 5.0.2 update. Thanks again for reporting.
